### PR TITLE
1615 remove guice and update oss

### PR DESCRIPTION
**Pull request by xsalefter**
- `DBIProvider` and `KillBillHealthCheckRegistry` still use Guice `@Inject` annotation
- remove unused dependency
- update `killbill-oss-version`, in attempt to fix `killbill` repository build.

### CODE REVIEW

**Comment by xsalefter** [comment]
@pierre @sbrossie Failed because:

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project killbill-config-magic: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test failed: A required class was missing while executing org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test: org/apache/maven/surefire/api/util/TempFileManager
Error:  -----------------------------------------------------
Error:  realm =    plugin>org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7-2044253910
Error:  strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
Error:  urls[0] = file:/home/runner/.m2/repository/org/apache/maven/plugins/maven-surefire-plugin/3.0.0-M7/maven-surefire-plugin-3.0.0-M7.jar
Error:  urls[1] = file:/home/runner/.m2/repository/org/apache/maven/surefire/surefire-junit47/3.0.0-M6/surefire-junit47-3.0.0-M6.jar
Error:  urls[2] = file:/home/runner/.m2/repository/org/apache/maven/surefire/common-junit48/3.0.0-M6/common-junit48-3.0.0-M6.jar
Error:  urls[3] = file:/home/runner/.m2/repository/org/apache/maven/surefire/common-junit4/3.0.0-M6/common-junit4-3.0.0-M6.jar
Error:  urls[4] = file:/home/runner/.m2/repository/org/apache/maven/surefire/common-junit3/3.0.0-M6/common-junit3-3.0.0-M6.jar
Error:  urls[5] = file:/home/runner/.m2/repository/org/apache/maven/surefire/common-java5/3.0.0-M6/common-java5-3.0.0-M6.jar
Error:  urls[6] = file:/home/runner/.m2/repository/org/apache/maven/surefire/surefire-grouper/3.0.0-M6/surefire-grouper-3.0.0-M6.jar
Error:  urls[7] = file:/home/runner/.m2/repository/org/apache/maven/surefire/surefire-api/3.0.0-M6/surefire-api-3.0.0-M6.jar
Error:  urls[8] = file:/home/runner/.m2/repository/org/apache/maven/surefire/surefire-logger-api/3.0.0-M6/surefire-logger-api-3.0.0-M6.jar
Error:  urls[9] = file:/home/runner/.m2/repository/org/apache/maven/surefire/maven-surefire-common/3.0.0-M7/maven-surefire-common-3.0.0-M7.jar
Error:  urls[10] = file:/home/runner/.m2/repository/org/apache/maven/surefire/surefire-extensions-api/3.0.0-M7/surefire-extensions-api-3.0.0-M7.jar
Error:  urls[11] = file:/home/runner/.m2/repository/org/apache/maven/surefire/surefire-booter/3.0.0-M7/surefire-booter-3.0.0-M7.jar
Error:  urls[12] = file:/home/runner/.m2/repository/org/apache/maven/surefire/surefire-extensions-spi/3.0.0-M7/surefire-extensions-spi-3.0.0-M7.jar
Error:  urls[13] = file:/home/runner/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/3.1.1/maven-common-artifact-filters-3.1.1.jar
Error:  urls[14] = file:/home/runner/.m2/repository/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
Error:  urls[15] = file:/home/runner/.m2/repository/org/codehaus/plexus/plexus-java/1.1.1/plexus-java-1.1.1.jar
Error:  urls[16] = file:/home/runner/.m2/repository/org/ow2/asm/asm/9.2/asm-9.2.jar
Error:  urls[17] = file:/home/runner/.m2/repository/com/thoughtworks/qdox/qdox/2.0.1/qdox-2.0.1.jar
Error:  urls[18] = file:/home/runner/.m2/repository/org/apache/maven/surefire/surefire-shared-utils/3.0.0-M7/surefire-shared-utils-3.0.0-M7.jar
Error:  Number of foreign imports: 1
Error:  import: Entry[import  from realm ClassRealm[project>org.kill-bill.commons:killbill-commons:0.25.1-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
Error:  
```

SO suggests that:
1. delete maven dir: https://stackoverflow.com/a/63489628/554958
2. add `maven-resource-plugin`: https://stackoverflow.com/a/46245829/554958 . I can try to add this, but still I think I need approval for that.
3. or perhaps just restart will work?

**Comment by pierre** [comment]
@xsalefter Restarts don't help :/ Also, there is no caching, so no `.m2` to delete.

Can you try to update the Maven version (you can override the version in the job definition: https://github.com/killbill/gh-actions-shared/blob/71f77cb205d9b3b5e8a6e3f2ee2886e52252b6f5/.github/workflows/ci.yml#L22)?

**Comment by xsalefter** [comment]
Alright, there are some other options, but lets update maven first: https://github.com/killbill/gh-actions-shared/pull/13

**Comment by pierre** [comment]
> Alright, there are some other options, but lets update maven first: [killbill/gh-actions-shared#13](https://github.com/killbill/gh-actions-shared/pull/13)

FWIW it looks like it's only the `jdbi` and `config-magic` jobs failing, restarting the others seem to work.

**Comment by xsalefter** [comment]
@pierre [updating surefire version](https://github.com/killbill/killbill-commons/pull/144/commits/d15e0e2c6fd0fdc41ff4226aedf542626b2085b1) to 3.0.0-M7 does the job.

**Review by pierre — APPROVED** [review]
Nice 👍 

It looks like the parent pom.xml already defines `-M7` (https://github.com/killbill/killbill-oss-parent/blob/17b5048cafb6fe6c80a58ce12c6163844dea214c/pom.xml#L2106) but better to override it here, so we keep the dependency in sync.

**Pull request merged**
